### ISSUE TITLE
Drop support for *.nb 

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Wolfram-Language-IntelliJ-Plugin-Archive#51]
After installation of the plugin the first thing to do is to drop *.nb from supported files and associate files with MMA executable.

I don't know if the latter is possible from plugin perspective but the former should be relatively easy to change.

p.s. Sometimes I want to open *.m files with MMA, I had to add MMA executable to external tools and I can open .m file from context menu. Maybe that could be automated too during installation?

**Comment by szhorvat** [comment]
So to make it clear, all we want is for notebook files to open with Mathematica by default, without having to change settings to achieve this.

**Comment by halirutan** [comment]
This should work now. It uses IntelliJ's methods to open notebooks (and cdf) natively through the operating system.
