### ISSUE TITLE
Not used local variables indicator

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Wolfram-Language-IntelliJ-Plugin-Archive#55]
I must say I find it useful, yet not essential. If it is easy to add it would be nice. 

Here is a screenshot with WWB enchanced Eclipse editor:

![image](https://cloud.githubusercontent.com/assets/15227576/18194793/8438656a-70e8-11e6-84e1-21d030cc2b3e.png)

**Comment by halirutan** [comment]
Sounds like a good plan. I will work on this.

**Comment by halirutan** [comment]
Just an update, due to my better understanding of the whole IDEA SDK, this is nothing for the near future. It's what I will work on very soon and I expect that it doesn't take long to implement.

**Comment by halirutan** [comment]
I will publish the first version of this with the next 2019.1.1 release. I'm sure there are a lot of edge-cases, but in general it should work for all local scopes

![img](http://i.imgur.com/0LwkGZg.png)
